### ISSUE TITLE
How to know which appvador ad is completed when screen have many ads?

### ISSUE THREAD

**Issue by vfa-thanghc** [appvador/AppVadorSample-3.0-iOS#1]
When an ad is completed, delegate "onCompletionAd" will be called.
If screen have many ads, delegate "onCompletionAd" will be called for all of ads when completed.
I'm not find any property to determine which ad is completed to handle something such as reload that one.
Could you please help me with this issue? Thanks.

**Comment by s-kageyama** [comment]
This issue was resolved in direct contact.
